import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

// Copies ERC-7730 descriptors from the upstream registry VERBATIM - all local
// curation (added formats, legacy contracts) lives in clearsig-repo.ts OURS.
//   node test/misc/build-clearsig.ts <registry-repo>
// <registry-repo> is a clear-signing-erc7730-registry git checkout. Writes:
// - the generated ERCS line inside src/advanced/clearsig-repo.ts (ercs/ files)
// - src/advanced/clearsig-repo-full.ts (registry/ files, no ercs/)

type Any = Record<string, any>;

const root = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const outDir = join(root, 'src', 'advanced');
const repo = process.argv[2];
if (!repo)
  throw new Error(
    'usage: node misc/build-clearsig.ts <clear-signing-erc7730-registry-repo>'
  );

const walk = (dir: string, base = ''): string[] => {
  const out: string[] = [];
  for (const item of readdirSync(join(dir, base), { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    const path = normalize(base ? `${base}/${item.name}` : item.name).replace(/\\/g, '/');
    if (item.isDirectory()) out.push(...walk(dir, path));
    else out.push(path);
  }
  return out;
};
const isDesc = (path: string) =>
  (path.startsWith('ercs/') || path.startsWith('registry/')) &&
  path.endsWith('.json') &&
  !path.includes('/tests/') &&
  !path.endsWith('.tests.json');
const sourceCommit = execFileSync('git', ['-C', repo, 'rev-parse', 'HEAD'], {
  encoding: 'utf8',
}).trim();
const build = (paths: string[]) => {
  const out: Record<string, Any> = {};
  for (const path of paths) {
    const src = join(repo, ...path.split('/'));
    if (!existsSync(src)) throw new Error(`missing registry file ${path}`);
    out[path] = JSON.parse(readFileSync(src, 'utf8'));
  }
  return out;
};
const source = 'ethereum/clear-signing-erc7730-registry';
const all = walk(repo).filter(isDesc);
const ercs = build(all.filter((p) => p.startsWith('ercs/')));
const registry = build(all.filter((p) => p.startsWith('registry/')));

// ERCS lives inside the hand-maintained clearsig-repo.ts: replace the marked line.
const repoTs = join(outDir, 'clearsig-repo.ts');
const marker = 'export const ERCS: Record<string, ClearSigDef> =';
const lines = readFileSync(repoTs, 'utf8').split('\n');
const at = lines.findIndex((l) => l.startsWith(marker));
if (at < 0) throw new Error(`marker not found in ${repoTs}`);
lines[at] = `${marker} /* @__PURE__ */ deepFreeze(${JSON.stringify(ercs)});`;
const stamp = lines.findIndex((l) => l.includes('// Generated by test/misc/build-clearsig.ts'));
if (stamp >= 0)
  lines[stamp] = `// Generated by test/misc/build-clearsig.ts from ${source}.`;
const commit = lines.findIndex((l) => l.includes('// Source commit:'));
if (commit >= 0) lines[commit] = `// Source commit: ${sourceCommit}.`;
writeFileSync(repoTs, lines.join('\n'), 'utf8');

writeFileSync(
  join(outDir, 'clearsig-repo-full.ts'),
  `import { deepFreeze } from '../utils.ts';\n` +
    `import type { ClearSigDef } from './clearsig.ts';\n\n` +
    `// Generated by test/misc/build-clearsig.ts from ${source}.\n` +
    `// Source commit: ${sourceCommit}.\n` +
    `// The full registry (no ercs/ - those ship inside CLEARSIG_REPO):\n` +
    `// Import this separate subpath only when needed; advanced/abi.js does not re-export it.\n` +
    `// decodeTx(tx, { clearSig: { ...CLEARSIG_REPO, ...CLEARSIG_REPO_FULL } })\n` +
    `// prettier-ignore\n` +
    `const REPOSITORY: Record<string, ClearSigDef> = ${JSON.stringify(registry)};\n` +
    `/** Full upstream ERC-7730 descriptor repository for callers that accept the larger bundle. */\n` +
    `export const CLEARSIG_REPO_FULL: Record<string, ClearSigDef> =\n` +
    `  /* @__PURE__ */ deepFreeze(REPOSITORY);\n`,
  'utf8'
);
console.log(`wrote ${Object.keys(ercs).length} ercs files into clearsig-repo.ts`);
console.log(`wrote ${Object.keys(registry).length} registry files into clearsig-repo-full.ts`);
